### ISSUE TITLE
Improve information about games directly on the list

### ISSUE THREAD

**Issue by Tintwo** [michelpereira/awesome-open-source-games#11]
Hello @michelpereira ,

I think it should be great if we can see inside your list about some games details, such as "still under development", "dead project", and so on.
This could make more readable this list, such as many lists which give details about "paid/free", "public/registered", etc.
How do you think about this ? (I can help for this)

Regards.

**Comment by michelpereira** [comment]
Hi, @Tintwo . That's a good one we should consider. But there's a strict guideline from the awesome-lists creator just to use the name of the item and its description.

I'll reach out to him and check if I can use this one in my awesome-list, as only mention games that area 'dead' or 'no development'.
