### ISSUE TITLE
 Double Damnation - FOSS Smash Bros Metroidvania #651 

### ISSUE THREAD

**Issue by TheYellowArchitect** [michelpereira/awesome-open-source-games#12]
I am the creator of [Double Damnation](https://ddamnation.com/) and would like to request to add it on this list. It has been released on [Steam](https://store.steampowered.com/app/1015190/Double_Damnation/) but ofc you can download an offline version at its own [repo](https://github.com/TheYellowArchitect/doubledamnation)

I request to add this, because damn it pains me to see so many opensource games are generic clones or bootleg. I wish for more opensource games like Battle for Wesnoth - I did my best, and so I want to share it to spread FOSS mentality, as it's a damn shame so many great games are closed source, and its normalized because "open source games are bad"

P.S. The github issue template is weird, and doesn't seem relevant to adding a game to the list.

**Comment by michelpereira** [comment]
@TheYellowArchitect Hi, there. Please clone the repo and submit a PR to have you as who added the request.

**Comment by TheYellowArchitect** [comment]
Done! https://github.com/michelpereira/awesome-open-source-games/pull/16
